### ISSUE TITLE
How can I get applications to start inside my workspace?

### ISSUE THREAD

**Issue by mingfang** [Glue42/core#231]
I have using the `workspaces-ui-react` and I want all my applications to be windows inside the workspace.
But applications that are started using `glue.appManager` and `glue.intents.raise` always run in popup windows.
How can I get the applications to run inside the workspace instead of popup windows?

**Comment by mingfang** [comment]
I basically what to achieve the result here 
https://github.com/Glue42/core/blob/b60a84e5bc2594b29fd3757a764c1371a513a493/tutorials/react/solution/stocks/src/glue.js#L183

in response to a `IntentRequest`.

**Comment by flashd2n** [comment]
Hi @mingfang

Currently `open` from the Windows API, `start` from the AppManager API and `raise` from the Intents API all open the application/window as a standalone popup and there is no way, via those APIs, to point to a workspace instead. The only way to add an app/window to a workspace is via the Workspaces API. The reason is that when adding an app to a workspace, the framework needs to know where exactly to put that app and when it comes to workspaces, the options are a lot. 

There is a possible workaround. Once you open an app/window you can get it's windowId via the Windows API or the instanceId via the AppManager API. Then you can use the Workspaces API to add that window to the workspace at a location of your choosing. You can do that via the `addWindow` method, which can work with either an `appName` or `windowId` -> this is the id of an existing window and/or the id of an existing application instance (they are the same).

Modifying the example you linked to, the functionality would be something like this:

`
// start a new app instance from the current window
const standAloneInstance = await glue.appManager.application("SomethingStandalone").start();

// Reference to the current window.
const myId = glue.windows.my().id;

// Reference to the immediate parent element of the Stocks window.
const myImmediateParent = myWorkspace.getWindow(window => window.id === myId).parent;

// Add a `Group` element as a sibling of the immediate parent of the Stocks window.
const group = await myImmediateParent.parent.addGroup();

// Add the existing standalone window in the newly created `Group` element.
detailsWorkspaceWindow = await group.addWindow({ windowId: standAloneInstance.id });
`

There are also other ways to obtain the id of a window/app -> you can also subscribe to the `onWindowAdded` event from the Windows API, for example.

All of the above is applicable when you open a window via `raise` -> the window will be available in the windows `list`, events will be fired upon creation and so on.

Let me know if that works for you.

**Comment by mingfang** [comment]
Thanks for the detailed response. 
I was hoping for a way to intercept or override the Platform’s default handler for application start and intents. 
I think I’m going to add interop methods and call them instead of the standard Platform methods. 
But please consider adding a way to override The default Platform behavior
