### ISSUE TITLE
Question: How can I prevent the Workspace React component from auto creating the "Untitled 1" workspace?

### ISSUE THREAD

**Issue by mingfang** [Glue42/core#234]
I'm building an application based on https://github.com/Glue42/core/tree/master/templates/workspaces-react and it's also the "main" app, I always see a default workspace called "Untitled 1". Also if it's the only workspace then I'm unable to close it.
It seems there's logic to maintain at least one open workspace.
Is there a way to prevent this behavior?

**Comment by flashd2n** [comment]
Hi @mingfang 

Yes, this is done on purpose. I am guessing your app's glue initialization looks something like this:

`
<GlueProvider settings={{
      webPlatform: {
        config: {
          glue: {
            libraries: [GlueWorkspaces]
          },
          workspaces: {
            src: "/",
            isFrame: true,
            frameCache: false
          },
        },
        factory: GlueWebPlatform
      },
    }}>
      <App />
    </GlueProvider>
`

The `isFrame` flag enables the logic you described. We have done this on purpose in an attempt to improve the end-user experience. When the workspace frame is the 'main' app, it hosts all of the Glue connection and transport logic. Therefore accidental closing of this app (by simply closing the last workspace) would result in lost Glue connection in any other remaining windows/apps/clients.

Here is a quick example. The user opens the app (which is a workspace frame and a main app at once), loads a workspace. Then the user decides to eject a one or more windows from the workspace (maybe to take advantage of multiple screens). Now at this moment, if the user closes the last remaining workspace in the frame and we also close the frame, the ejected windows will lose their Glue connection. We believe this will introduce confusion in the end-user and that is why by default we keep at least one workspace in the main workspace frame, **unless** it is explicitly closed by the API (frame.close()) or by the user by clicking the window close button.
 
Understandably, there might be use cases where you want that behavior changed. It is on our roadmap to introduce means to plug-in and redefine the default behavior of the close buttons and any other button in the headers. However, this is not expected soon, but there is another way.

In your workspaces frame app you can subscribe to `glue.workspaces.onWorkspaceClosed()`. Once this event is fired, you can check and see what is left in the frame. If there is only one workspace in then frame and this workspace has no windows, then you can explicitly close it via `frame.close()`. The problem here is that we checked and the `onWorkspaceClosed` event does not fire correctly for the last workspace in a frame which is also a main app. But, we have scheduled a fix and it will be ready early next week. The PR will be linked to this issue for easy tracking.

**Comment by mingfang** [comment]
@flashd2n 
Thanks for the amazing explanation. 
I think it makes sense to always keep one workspace open, I just wish it can be a workspace I designate and not an empty "Untitled 1" workspace.
I'm going to follow where the `isFame` flag is used and see if I can hack around it.
Thanks again for your help.

**Comment by flashd2n** [comment]
No problem :) You can definitely follow the `isFrame` logic, modify and rebuild the @glue42/workspaces-ui-core package, but I would recommend waiting a few days for us to fix the `onWorkspaceClosed` event and use the logic I suggested.

Providing a "default" workspace to be used instead of an empty `Untitled` one makes sense, we will look into that.

**Comment by mingfang** [comment]
I put together a demo here of what I'm working on
https://glue42-example.rebelsoft.com/

What you see initially is the default behavior, showing an empty workspace.
Press the "Click Here" button to see my desired behavior.
Basically I want the "Welcome" workspace as the default.

My code is here https://github.com/mingfang/glue42-workspace

**Comment by mingfang** [comment]
I updated my demo to auto restore a set of workspaces on startup using a glue42 plugin.
I still had to use a hack to close the unwanted "Untitled 1" workspace.
All I need now is to have a glue42 settings option to disable the default workspace.

**Comment by flashd2n** [comment]
@mingfang The demo looks sleek! We planned and will begin working on adding options to enable, disable and/or configure the "default" workspace. I will make sure to like the PR with this issue when it is opened.

**Comment by flashd2n** [comment]
Also, you might want to check out this:

https://github.com/Glue42/core/blob/master/packages/dev-workspaces-frame/src/App.tsx

Here you can see how we force the frame to load a specific workspace platform on load. Basically, we restore a workspace and reuse the existing workspace's (the default one) id. This reduces (does not completely removes) the initial flick that shows the default workspace. Note that the method `getFrameId()` is exported by `@glue42/workspaces-ui-react`, so if what to use that logic, just modify the import like this:

import Workspaces, { getFrameId } from "@glue42/workspaces-ui-react";

**Comment by mingfang** [comment]
@flashd2n
I will check that out. Thanks!
