### ISSUE TITLE
iOS / Android / Safari Support by optionally moving shared workers to Service Worker

### ISSUE THREAD

**Issue by petyosi** [Glue42/core#29]
Shared web workers are supported only in a subset of the [desktop versions of the browsers](https://caniuse.com/#feat=sharedworkers). We can provide a recipe for moving the interop layer to [the service worker, which is supported practically everywhere](https://caniuse.com/#feat=serviceworkers). As far as I remember, there are certain limitations of this approach - [the Service Worker Security FAQ states the following](https://chromium.googlesource.com/chromium/src/+/master/docs/security/service-worker-security-faq.md):

> Chrome terminates a SW if the SW has been idle for 30 seconds. Chrome also detects long-running workers and terminates them. It does this if an event takes more than 5 minutes to settle, or if the worker is busy running synchronous JavaScript and does not respond to a ping within 30 seconds.

**Comment by lspiro-Tick42** [comment]
Safari support will be useful because many of us who do demos rather than real work use Macs :).  

I think the iOS/Android support will be very important as we add support for 'multi app' workspaces.

**Comment by flashd2n** [comment]
We have tried a number of different approaches and we couldn't find a reliable solution, which doesn't require major rework/extension of the existing environment logic.

We explored the idea of moving the Shared Worker logic to a Service Worker for platforms, which does not support Shared Worker. However, the Service Worker is designed primarily as a proxy and its lifecycle is managed by the browser independently of any scripts or pages. This essentially means that the logic defined in the worker will be available "when needed". The issue here is that when the worker is "needed", it is started, which means the logic is reran, which in turns means that the gateway is reinitialized. 

1. Glue42 Core needs a constant reliable connection to the Environment (worker and gateway). The idea of frequent restarts of the gateway and client reconnections with correct state is something which would require a ton of effort to implement. And even then, it is questionable if it would perform reliably for functionalities like interop streaming, contexts/windows events, servers/methods discovery, etc.

2. Another approach we tried was to prevent the service worker from stopping as long as there is an open Client, but every "workaround" or "hack" we tried proved to be unreliable in any reasonable time and the results differed greatly from platform to platform.

3. We explored the idea of "decentralizing" the worker+gateway logic. Even though this would also require considerable extension of the Environment logic, this proved to be a reliable solution. The idea is that instead of "one source of truth" (the Shared Worker), each Client will have a dedicated worker and the dedicated workers can then communicate with each other through BroadcastChannel API or an appropriate polyfill.

At the moment it is still unclear how critical the support for "non-shared worker platforms" (Safari and mobile - iOS/Android) is for the users. This issue remains open as we continue to explore more approaches to the problem and monitor users' interest in support for these platforms.

**Comment by lspiro-Tick42** [comment]
I am OK with dropping Shared Workers.

I would then like to suggest a separate issue, about enabling use of 'remote Glue42 Gateway'  by Glue42 Core applications. 

I assume that this would require the use of an external, typically cloud hosted, Glue42 Gateway. This is part of our proprietary product, but the main use case for Safari IMO is from Tablets and possibly (much less likely) phones would all require an external Gateway anyway.
