### ISSUE TITLE
[BUG] Tutorial solution crashes after a period of inactivity

### ISSUE THREAD

**Issue by nareshbhatia** [Glue42/core#331]
**Describe the bug**

**To Reproduce**
1. Build the React tutorial solution
2. Launch the Clients app. Interact with it to open client details etc.
3. Leave the application up for about 20 minutes.
4. Try to interact with the Clients window. You will see the following error:

![CleanShot 2022-02-24 at 14 36 35](https://user-images.githubusercontent.com/1220198/155595146-1d9c6e2a-eed7-41c5-bc8c-94f9864b4f2b.png)

5. Close the application and reopen it. Everything works fine again.

**Expected behavior**
Application does not crash for long period of operation.

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 98.0.4758.102

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by flashd2n** [comment]
Hi @nareshbhatia and thanks for reaching out. This issues was caused by a bug which was fixed long ago, but we didn't update all the necessary packages in the tutorials directory. We are working on a number of fixes and improvements to our React tutorials and this fix will come with it within the next few days.

**Comment by nareshbhatia** [comment]
Thanks @flashd2n. Good to know.
