### ISSUE TITLE
[BUG] The `worker` property in the config object when initializing the Glue42 Web library is ignored

### ISSUE THREAD

**Issue by arjunah** [Glue42/core#59]
The optional `worker` property in the config object passed to the `GlueWeb()` factory function when initializing the Glue42 Web library is ignored, unless the optional `extends` property is defined.

Assuming there is no `glue.config.json` and the shared worker and the Glue42 Gateway files are in a top-level "/lib" directory, this will not work (the library will not initialize):
`window.glue = await GlueWeb({ worker: "/lib/worker.js" });`

But this will work:
`window.glue = await GlueWeb({ extends: false, worker: "/lib/worker.js" });`

**Comment by kirilpopov** [comment]
By default extend is set to */glue/glue.config.json* in @glue42/web config - this means that @glue42/web will get the config from the default location if you not specify extend option.

If you mix this with setting a custom worker it results in, the config becomes:
```javascript
{
  worker: "pathA",
  extends: "defaultPath"
}
```

This is problematic, because the shared worker and the app should use the same configuration file, however in the example above the app will use config from defaultPath and the worker will search config from PathA (worker always expect his configuration to be on the same level as it)

I think the best option here is to add an error if you specify just worker, asking you to either turn off extend (by setting it to false), or to set it to another value.

Another option is to auto turn off extend (setting it to false internally), however this makes the default value of extend different in different situations which is not great.
